# 应用名称
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.122.160:3306/loafblog_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 192.168.145.132
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write_dates_as_timestamps: false
    time-zone: GMT+8
  sleuth:
    web:
      client:
        enabled: true
    sampler: #采样率，默认0.1 即10条消息有一条被记录
      rate: 1
  zipkin:
    base-url: http://192.168.145.132:9411 #地址
    enabled: true
    sender:  #追踪消息类型
      type: rabbit
  rabbitmq:
    username: guest
    password: guest
    host: 192.168.145.132
    port: 5672
    publisher-returns: true
    publisher-confirm-type: correlated
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 应用服务 WEB 访问端口
server:
  port: 7000
logging:
  level:
    com.thciwei.loafblog.blog: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true



