name: Master-Docker-Images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: loafblog
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: docker/setup-buildx-action@v1

      - name: Maven Install
        run: |
          echo '======= 开始mvn clean ======='
          mvn clean

          echo '======= 开始mvn install&&package ======='
          mvn install -DskipTests=true &&  mvn package -DskipTests=true

      - name: 构建前端镜像 Build vue web
        run: |
          echo '======= 开始构建loafblog_vue ======='

          cd ./loafblog_vue

          npm install
          npm run build
          docker build -t registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog_vue .
          cd ..
          echo '======= 开始构建前端镜像 ======='
          echo '======= 开始构建loafblog_vue_web ======='
          cd ./loafblog_vue_web
          npm install
          npm run build
          docker build -t  registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog_vue_web .
          cd ..





      - name: Build Server Images
        run: |
          echo '======= 开始构建后端镜像 ======='

          echo '======= 开始构建renren-fast ======='
          cd renren-fast
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-blog ======='
          cd loafblog-blog
          mvn docker:build
          cd ..



          echo '======= 开始构建loafblog-gateway ======='
          cd loafblog-gateway
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-auth-server ======='
          cd loafblog-auth-server
          mvn docker:build
          cd ..
          echo '======= 开始构建loafblog-mail ======='
          cd loafblog-mail
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-picture ======='
          cd loafblog-picture
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-search ======='
          cd loafblog-search
          mvn docker:build
          cd ..




      # 登录到 阿里云镜像服务，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器
      - name: Login to Aliyun
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_USER_NAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}


      - name: Push Docker Image
        run: |
          echo '=====开始上传镜像====='

          echo '======= 开始上传loafblog_vue ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog_vue
          echo '======= 开始上传renren-fast ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/renren-fast
          echo '======= 开始上传loafblog-blog ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog-blog
          echo '======= 开始上传loafblog_vue_web ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog_vue_web

          echo '======= 开始上传loafblog-gateway ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog-gateway

          echo '======= 开始上传loafblog-auth-server ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog-auth-server
          
          echo '======= 开始上传loafblog-mail ======='
          docker push thciwei/loafblog-mail

          echo '======= 开始上传loafblog-picture ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog-picture

          echo '======= 开始上传loafblog-search ======='
          docker push registry.cn-hangzhou.aliyuncs.com/thciwei/loafblog-search
          echo '=====镜像上传结束====='

#      - name: 部署到服务器 Start loafblog
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          password: ${{ secrets.REMOTE_PASSWORD }}
#          port: ${{ secrets.PORT }}
#          script: |
#            cd /root/loafblog
#            docker-compose up -d