name: Master-Docker-Images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: loafblog
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: docker/setup-buildx-action@v1

      - name: Maven Install
        run: |
          echo '======= 开始mvn clean ======='
          mvn clean

          echo '======= 开始mvn install&&package ======='
          mvn install -DskipTests=true &&  mvn package -DskipTests=true

      - name: 构建前端镜像Build vue web
        run: |
          echo '======= 开始构建前端镜像 ======='
          echo '======= 开始构建loafblog_vue_web ======='
          cd ./loafblog_vue_web
          npm install
          npm run build
          docker build -t  thciwei/loafblog_vue_web .
          cd ..





      - name: 构建后端镜像Build Server Images
        run: |
          echo '======= 开始构建后端镜像 ======='

          echo '======= 开始构建loafblog-blog ======='
          cd loafblog-blog
          mvn docker:build
          cd ..



          echo '======= 开始构建loafblog-gateway ======='
          cd loafblog-gateway
          mvn docker:build
          cd ..


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: 推送镜像push Images to DockerHub
        run: |
          docker images
          echo '======= 开始上传镜像 ======='

  
         
          echo '======= 开始上传loafblog-blog ======='
          docker push thciwei/loafblog-blog


          echo '======= 开始上传loafblog_vue_web ======='
          docker push thciwei/loafblog_vue_web


          echo '======= 开始上传loafblog-gateway ======='
          docker push thciwei/loafblog-gateway




          echo '=====镜像上传结束======'
          echo '=====开始自动部署======'

      - name: 部署到服务器 Start loafblog
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/loafblog
            docker-compose up -d