name: Master-Docker-Images



on:
  push:
    branches: master



jobs:

  build:
    runs-on: ubuntu-latest
    environment: loafblog
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: docker/setup-buildx-action@v1

      - name: Maven Install
        run: |
          echo '======= 开始mvn clean ======='
          mvn clean

          echo '======= 开始mvn install&&package ======='
          mvn install -DskipTests=true &&  mvn package -DskipTests=true

      - name: Build vue web
        run: |
          echo '======= 开始构建前端镜像 ======='
          echo '======= 开始构建loafblog_vue ======='
          cd ./loafblog_vue
          npm install
          npm run build
          echo '== 防止index页面无效 =='
          npm install -g http-server
          cd ..

          echo '======= 开始构建loafblog_vue_web ======='
          cd ./loafblog_vue_web
          npm install
          npm run build
          cd ..

      - name: Build Server Images
        run: |
          echo '======= 开始构建后端镜像 ======='
          echo '======= 开始构建loafblog-auth-server ======='
          cd loafblog-auth-server
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-blog ======='
          cd loafblog-blog
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-gateway ======='
          cd loafblog-gateway
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-mail ======='
          cd loafblog-mail
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-picture ======='
          cd loafblog-picture
          mvn docker:build
          cd ..

          echo '======= 开始构建loafblog-search ======='
          cd loafblog-search
          mvn docker:build
          cd ..

          echo '======= 开始构建renren-fast ======='
          cd renren-fast
          mvn docker:build
          cd ..


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      - name: push Images to DockerHub
        run: |
          docker images
          echo '======= 开始上传镜像 ======='
          echo '======= 开始上传loafblog-auth-server ======='

          docker push thciwei/loafblog-auth-server

          echo '======= 开始上传loafblog-blog ======='
          docker push thciwei/loafblog-blog

          echo '======= 开始上传loafblog-gateway ======='
          docker push thciwei/loafblog-gateway

          echo '======= 开始上传loafblog-mail ======='
          docker push thciwei/loafblog-mail

          echo '======= 开始上传loafblog-picture ======='
          docker push thciwei/loafblog-picture

          echo '======= 开始上传loafblog-search ======='
          docker push thciwei/loafblog-search

          echo '======= 开始上传renren-fast ======='
          docker push thciwei/renren-fast

          echo '======= 开始上传loafblog_vue_web ======='
          docker push thciwei/loafblog_vue_web

          echo '======= 开始上传loafblog_vue ======='
          docker push thciwei/loafblog_vue



          echo '=====镜像上传结束====='